// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQUo3xkyYZaqUL0w6Ox6ER0Cc3ezMcDXs',
    appId: '1:698968277337:web:eaeb9e0f8e49b409e90c48',
    messagingSenderId: '698968277337',
    projectId: 'invoice-app-184f1',
    authDomain: 'invoice-app-184f1.firebaseapp.com',
    storageBucket: 'invoice-app-184f1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCdnT7S1Rh2xXIWEPqShAhmmh5cN246Pk',
    appId: '1:698968277337:android:72b48ca72d68c8d0e90c48',
    messagingSenderId: '698968277337',
    projectId: 'invoice-app-184f1',
    storageBucket: 'invoice-app-184f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6BjnUIoFKq_Xs0_sFgR2bzQFgwt8PUIw',
    appId: '1:698968277337:ios:3c25e7642d7edb9de90c48',
    messagingSenderId: '698968277337',
    projectId: 'invoice-app-184f1',
    storageBucket: 'invoice-app-184f1.firebasestorage.app',
    iosBundleId: 'com.example.invoiceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6BjnUIoFKq_Xs0_sFgR2bzQFgwt8PUIw',
    appId: '1:698968277337:ios:3c25e7642d7edb9de90c48',
    messagingSenderId: '698968277337',
    projectId: 'invoice-app-184f1',
    storageBucket: 'invoice-app-184f1.firebasestorage.app',
    iosBundleId: 'com.example.invoiceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQUo3xkyYZaqUL0w6Ox6ER0Cc3ezMcDXs',
    appId: '1:698968277337:web:fd726b7e7117bc0de90c48',
    messagingSenderId: '698968277337',
    projectId: 'invoice-app-184f1',
    authDomain: 'invoice-app-184f1.firebaseapp.com',
    storageBucket: 'invoice-app-184f1.firebasestorage.app',
  );
}
